[package]
name = "crate-a"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
crate-b = { path = "../crate-b" }
crate-c = { path = "../crate-c" }
uniffi = { version = "0.29.4" }

[build-dependencies]
uniffi = { version = "0.29.4", features = ["build"] }
